import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { MidjourneyForm } from "../components/MidjoyrneyForm"
import styles from "../styles/Home.module.css"
import "@fontsource/roboto/300.css"
import "@fontsource/roboto/400.css"
import "@fontsource/roboto/500.css"
import "@fontsource/roboto/700.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Midjourney Generator</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>Midjourney Generator</h1>

        <MidjourneyForm />
      </main>

      <footer className={styles.footer}>Created by: Robert Bowes</footer>
    </div>
  )
}

export default Home
